--Usar MySQL para rodar os scripts abaixo
CREATE TABLE demonstracoes_contabeis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
    REG_ANS TEXT,
    CD_CONTA_CONTABIL TEXT,
    DESCRICAO TEXT,
    VL_SALDO_INICIAL DECIMAL(17,2),
    VL_SALDO_FINAL DECIMAL(17,2)
);

LOAD DATA LOCAL INFILE
'C:/Users/Usuario/Downloads/4T2024.csv'
INTO TABLE demonstracoes_contabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO,  VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE
'C:/Users/Usuario/Downloads/3T2024.csv'
INTO TABLE demonstracoes_contabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO,  VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE
'C:/Users/Usuario/Downloads/2T2024.csv'
INTO TABLE demonstracoes_contabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO,  VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE
'C:/Users/Usuario/Downloads/1T2024.csv'
INTO TABLE demonstracoes_contabeis
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO,  VL_SALDO_INICIAL, VL_SALDO_FINAL);


